image: python:3.9

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "trunk"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  LABELINFO_STATIC_COMMIT: "$CI_COMMIT_SHORT_SHA"

cache:
  paths:
    - .cache/pip
    - env/

before_script:
  - python --version 
  - python3 -m venv env
  - source env/bin/activate

install_deps:
  stage: build
  script:
    - pip3 install .

build:
  stage: build
  needs: [install_deps]
  script:
    - bash deployment/scripts/fetch_barcode_conf.sh 
    - python3 -m labelinfo -d "decoders" -c 'barcode_configuration.json' freeze
  artifacts:
    paths:
      - build/

make_decoder_js:
  stage: build
  script:
    - mkdir -p build/js
    - cat labelinfo/static/js/barcode_decode.js decoders/*.js > build/js/hgcal_barcode_decoding.js
    - cp barcode_configuration.json build/js/
  artifacts:
    paths:
      - build/js/hgcal_barcode_decoding.js

pages:
  stage: deploy
  script:
    - mv build/staticsite/ public/
  rules:
    - if: '$CI_COMMIT_BRANCH == "trunk"'
  artifacts:
    paths:
      - public

